/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [PatientID]
      ,[SIN]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Age]
      ,[City]
      ,[Province]
      ,[PostalCode]
      ,[StreetName]
      ,[StreetNumber]
      ,[ApartmentNumber]
      ,[MobilePhone]
      ,[HomePhone]
      ,[PrimaryDoctorID]
      ,[Disease]
      ,[Treatment]
      ,[NumberOfDaysAdmitted]
      ,[TotalFee]
  FROM [Hospital].[dbo].[Patient]